spring: 
  application: 
    name: hystrix-dashboard-turbineccc
server: 
  port: 22002
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://peer1:20001/eureka/
#      register-with-eureka: false
#      fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: refresh

turbine: 
  appConfig: spring-cloud-client-a
  aggregator: 
    clusterConfig: default
  clusterNameExpression: new String("default")
